#!/usr/bin/env bundle exec ruby 

Bundler.require(:script_bitly)

username = ENV["BITLY_USERNAME"] 
api_key  = ENV["BITLY_API_KEY"]
usage("$BITLY_USERNAME not set") unless username
usage("$BITLY_API_KEY not set")  unless api_key
Bitly.use_api_version_3
b = Bitly.new(username, api_key)
u = b.shorten(ARGV.first)
puts u.short_url

# vim:ft=ruby
